insert into items(cover_link, item_name,
                    price, description,
                    type_id) values
                                 ('https://api.rivegauche.ru/medias6/product-base-957707-0-listingDesktop?context=bWFzdGVyfHByb2R1Y3RzfDgyOTh8aW1hZ2UvanBlZ3xwcm9kdWN0cy9oZTEvaDgxLzExNTAyMTM0NzU1MzU4LmpwZ3w1YzQ1ZjkyZDA4YWM2MzhlM2Q5NzNlNTIwZDE2ODg1OTVhMjExNzcyMzA1NDRlZDVmMGYyMTFlYjViYmM3Yzdm',
                                  'Estee Lauder', 4970, 'https://rivegauche.ru/product/estee-lauder-beautiful-magnolia-eau-de-parfum-30', 1),
                                 ('https://api.rivegauche.ru/medias6/product-base-1018940-0-listingDesktop?context=bWFzdGVyfHByb2R1Y3RzfDg3MTR8aW1hZ2UvanBlZ3xwcm9kdWN0cy9oNDYvaDc2LzExNDc1MjA4MjQxMTgyLmpwZ3w0YjBkNTk1MTM1ZTJlNzcyOTcxMGE3NTQzNTVlOGM4ZmE0OTE1NDQzMjJmYzYxNTIxYzFkMjM4OWU5M2I0YzYx', 'Carolina Herrera Good Girl Blush', 6157, 'https://rivegauche.ru/product/carolina-herrera-good-girl-blush-eau-de-parfum-30', 1),
                                 ('https://api.rivegauche.ru/medias6/product-base-768964-0-listingDesktop?context=bWFzdGVyfHByb2R1Y3RzfDk5MjZ8aW1hZ2UvanBlZ3xwcm9kdWN0cy9oMjUvaDNmLzExNDc2MDk5MjM1ODcwLmpwZ3wzM2EyMmVlMGZhNDdkNzhhNDYyZmNkNDY2NjdjNzhkMTFjN2NiZGI0MGU0Mzk0ZjRkZWVkNTcwNzNkM2Y5YjA2', 'Paco Rabanne Invictus Eau de Toilette', 6011, 'https://rivegauche.ru/product/paco-rabanne-invictus-eau-de-toilette-50', 1),
                                 ('https://api.rivegauche.ru/medias6/product-base-937332-0-listingDesktop?context=bWFzdGVyfHByb2R1Y3RzfDExNzUyfGltYWdlL2pwZWd8cHJvZHVjdHMvaGYzL2g4MC8xMTQ4Mzk2ODA3Nzg1NC5qcGd8NDY4MzQ5NTVhMzNlOTcyYzMxMTAyZWNmNzA0ZDNlMTA0MDkxZWZlM2Y5YzIxNTFhN2MxZWM4ZTBkNDI2NWJjZA', 'MAC Powder Kiss Liquid Lipcolour', 2790, 'https://rivegauche.ru/product/mac-powder-kiss-liquid-lipstick-billion-smile', 2),
                                 ('https://api.rivegauche.ru/medias6/-normal-base-1015249-big-716170301181.jpg-listingDesktop?context=bWFzdGVyfGltYWdlc3wxMjUxNXxpbWFnZS9qcGVnfGltYWdlcy9oZGUvaDU4LzExNTU0Mzg4ODM2MzgyLmpwZ3w0MTYzYmRmNjA5MTc2NWEwZmQ2MGZmNmUzM2JlNTNiODFjYzQ4NTgzNjNiY2JmY2EwY2ZhZmNjNjk5Yjc5NzQ0', 'Bobbi Brown x Ethar Balkhair Luxe Lip Color', 3075, 'https://rivegauche.ru/product/bobbi-brown-x-ethar-balkhair-luxe-lip-color-neutral-rose', 2),
                                 ('https://api.rivegauche.ru/medias6/product-base-888705-0-listingDesktop?context=bWFzdGVyfHByb2R1Y3RzfDEwOTk1fGltYWdlL2pwZWd8cHJvZHVjdHMvaDYyL2g4Zi8xMTQ4MzM0ODA0MTc1OC5qcGd8NzZhZTkxMjBhNzgwMDI4NWRmZjUxZWRiNDdmYWQ3NjQ1YzFlZWQzOThkMTZhYjM1YmM3MmQzZjVmNWQ3MWQ4Yg', 'MAC Eye Brows Styler', 1990, 'https://rivegauche.ru/product/mac-eye-brows-styler-brunette', 3),
                                 ('https://api.rivegauche.ru/medias6/product-base-944058-0-listingDesktop?context=bWFzdGVyfHByb2R1Y3RzfDE0ODI2fGltYWdlL2pwZWd8cHJvZHVjdHMvaDVjL2gzNC8xMTQ3NDA4NDgyMzA3MC5qcGd8ZjRmNGI3OTFhMzZmMmQzMGU4MDI5ZDYwMzBjNjhiNzhhZDk3OWFhOTQ5NDEyNTlhMzY3YTFjZWQ3NDVjZWZiYg', 'Guerlain Mad Eyes Mascara', 2850, 'https://rivegauche.ru/product/guerlain-mad-eyes-mascara-1-cherniy', 4),
                                 ('https://api.rivegauche.ru/medias6/?context=bWFzdGVyfHByb2R1Y3RzfDEwODYxOXxpbWFnZS9qcGVnfHByb2R1Y3RzL2gxYS9oYjgvMTE0ODYzMTQyOTk0MjIuanBnfGRkZTZjYmRlODM2OGQyYmIyODQ2MmRlOWU4YTI4MjY1NTE1YzNhZjc5YzA3NDc3MzhmNjgxZjAyZDc5NDAzZjI', 'Bobbi Brown Smokey Eye Mascara Mini', 1500, 'https://rivegauche.ru/product/bobbi-brown-smokey-eye-mascara-mini', 4);